FROM alpine 3.15.0

LABEL version ="Alpine 3.15.0" maintainer="Radouane" os="Linux"

ENV CONTAINER_USER="Radouane"   
RUN useradd --system $CONTAINER_USER 
CMD [ "echo", "hello-alpine, I’m Radouane and this is a container from my first image" ]
